name: 04 - Using Actions

run-name: 04 - Using Actions

on:
    push:

env:
    directory: 04-using-actions/my-app

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4

            - name: Print Folder Structure
              run: ls
              working-directory: ${{env.directory}}

            - name: Install Dependencies
              run: npm ci 
              working-directory: ${{env.directory}}

            - name: Running Test
              run: npm run test
              working-directory: ${{env.directory}}

    
