name: 05 - 1 - Event Filters and Activity Types

run-name: 02 - 1 - Event Filters and Activity Types

on:
    push:
        branches: [main]
    pull_request:
        types: [opened, synchronize]

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Run
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"

    
