name: 06 - Contexts

run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on:
    workflow_dispatch:
        inputs:
            debug:
                description: Debug
                type: boolean
                required: false
                default: true

env:
    MY_WORKFLOW_VAR: 'workflow'
    MY_OVERWRITTEN_VAR: 'workflow'

jobs:
    echo-data:
        runs-on: ubuntu-latest
        env:
            MY_JOB_JAR: 'job'
            MY_OVERWRITTEN_VAR: 'job'
        steps:
            - name: Display Information
              run: |
                echo "${{github.event_name}}"
                echo "${{github.ref}}"
                echo "${{github.sha}}"
                echo "${{github.actor}}"
                echo "${{github.workflow}}"
                echo "${{github.run_id}}"
                echo "${{github.run_number}}"

            - name: Retrieve Variables 
              run: echo ${{vars.MY_VAR}}

            - name: Print Env Variables - Step
              run: |
                echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"
              env:
                MY_OVERWRITTEN_VAR: 'step'

            - name: Prinv Env Variables - Global
              run: |
                echo "Workflow env: ${{env.MY_WORKFLOW_VAR}}"
                echo "Overwritten env: ${{env.MY_OVERWRITTEN_VAR}}"

    
