name: 15 - Working with Matrices

on:
    workflow_dispatch:


jobs:
    backward-compatibility:
        runs-on: ubuntu-latest
        name: ${{matrix.os}}-${{matrix.version}}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                version: [18.x, 20.x, 21.x]
        steps:
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.version}}



