name: 17 - 1 - Custom Actions - Composite

run-name: 17 - 1 - Custom Actions - Composite | Env - ${{inputs.target-env}} | Version - ${{inputs.node-version}}

env:
    working-directory: 17-custom-actions/react-app

on:
    workflow_dispatch:
        inputs:
            target-env:
                description: Environment
                type: choice
                options: [dev, staging, production]
            node-version:
                description: Node Version
                type: choice
                options: [18.x, 20.x, 21.x]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{env.working-directory}}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                node-version: ${{inputs.node-version}}
                working-dir: ${{env.working-directory}}

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build

