name: 17 - 3 - Custom Actions - Docker

on:
    workflow_dispatch:
        inputs:
            url:
                description: URL
                type: string
                required: false
                default: "https://www.google.com"
            max_trials:
                description: Maximum trials until action fails
                type: number
                required: false
                default: '10'
            delay:
                description: Delay in seconds between trials
                type: number
                required: false
                default: '5'

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{inputs.url}}
