name: 18 - 1 - Resusable Workflows - Reusable Definition

on:
    workflow_call:
        inputs:
            target-directory:
                description: Target Directory
                type: string
                required: true
        outputs:
            build-status:
                description: The status of the build process
                value: ${{jobs.deploy.outputs.deploy-status}}
            url:
                description: The url of the deployed version
                value: ${{jobs.deploy.outputs.url}}

jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            build-status: ${{steps.build.outputs.build-status}}
            url: ${{steps.deploy.outputs.url}}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Build
              id: build
              run: |
                echo "Building using directory ${{inputs.target-directory}}"
                echo "build-status=success" >> $GITHUB_OUTPUT

            - name: Deploy
              id: deploy
              run: |
                echo "Deploying build artifacts"
                echo "url=https://www.google.com" >> $GITHUB_OUTPUT

